FROM n8nio/n8n:latest

ENV N8N_BASIC_AUTH_ACTIVE=true \
    N8N_HOST=0.0.0.0 \
    N8N_PORT=5678 \
    N8N_PROTOCOL=http \
    N8N_EDITOR_BASE_URL=https://n8n-signpost.azurewebsites.net \
    N8N_PUBLIC_API_BASE_URL=https://n8n-signpost.azurewebsites.net

CMD ["n8n"]
