export const languages = [
  { label: "Afrikaans", value: "af" },
  { label: "Afrikaans (South Africa)", value: "af-ZA" },
  { label: "Albanian", value: "sq" },
  { label: "Albanian (Albania)", value: "sq-AL" },
  { label: "Amharic", value: "am" },
  { label: "Amharic (Ethiopia)", value: "am-ET" },
  { label: "Arabic", value: "ar" },
  { label: "Arabic (Algeria)", value: "ar-DZ" },
  { label: "Arabic (Bahrain)", value: "ar-BH" },
  { label: "Arabic (Egypt)", value: "ar-EG" },
  { label: "Arabic (Iraq)", value: "ar-IQ" },
  { label: "Arabic (Jordan)", value: "ar-JO" },
  { label: "Arabic (Kuwait)", value: "ar-KW" },
  { label: "Arabic (Lebanon)", value: "ar-LB" },
  { label: "Arabic (Libya)", value: "ar-LY" },
  { label: "Arabic (Morocco)", value: "ar-MA" },
  { label: "Arabic (Oman)", value: "ar-OM" },
  { label: "Arabic (Qatar)", value: "ar-QA" },
  { label: "Arabic (Saudi Arabia)", value: "ar-SA" },
  { label: "Arabic (Syria)", value: "ar-SY" },
  { label: "Arabic (Tunisia)", value: "ar-TN" },
  { label: "Arabic (UAE)", value: "ar-AE" },
  { label: "Arabic (Yemen)", value: "ar-YE" },
  { label: "Armenian", value: "hy" },
  { label: "Armenian (Armenia)", value: "hy-AM" },
  { label: "Azerbaijani", value: "az" },
  { label: "Azerbaijani (Azerbaijan)", value: "az-AZ" },
  { label: "Basque", value: "eu" },
  { label: "Basque (Spain)", value: "eu-ES" },
  { label: "Belarusian", value: "be" },
  { label: "Belarusian (Belarus)", value: "be-BY" },
  { label: "Bengali", value: "bn" },
  { label: "Bengali (Bangladesh)", value: "bn-BD" },
  { label: "Bengali (India)", value: "bn-IN" },
  { label: "Bosnian", value: "bs" },
  { label: "Bosnian (Bosnia and Herzegovina)", value: "bs-BA" },
  { label: "Bulgarian", value: "bg" },
  { label: "Bulgarian (Bulgaria)", value: "bg-BG" },
  { label: "Burmese", value: "my" },
  { label: "Burmese (Myanmar)", value: "my-MM" },
  { label: "Catalan", value: "ca" },
  { label: "Catalan (Spain)", value: "ca-ES" },
  { label: "Chinese (Simplified)", value: "zh-CN" },
  { label: "Chinese (Traditional)", value: "zh-TW" },
  { label: "Chinese (Hong Kong)", value: "zh-HK" },
  { label: "Chinese (Macau)", value: "zh-MO" },
  { label: "Chinese (Singapore)", value: "zh-SG" },
  { label: "Croatian", value: "hr" },
  { label: "Croatian (Croatia)", value: "hr-HR" },
  { label: "Czech", value: "cs" },
  { label: "Czech (Czech Republic)", value: "cs-CZ" },
  { label: "Danish", value: "da" },
  { label: "Danish (Denmark)", value: "da-DK" },
  { label: "Dutch", value: "nl" },
  { label: "Dutch (Belgium)", value: "nl-BE" },
  { label: "Dutch (Netherlands)", value: "nl-NL" },
  { label: "English", value: "en" },
  { label: "English (Australia)", value: "en-AU" },
  { label: "English (Canada)", value: "en-CA" },
  { label: "English (Hong Kong)", value: "en-HK" },
  { label: "English (India)", value: "en-IN" },
  { label: "English (Ireland)", value: "en-IE" },
  { label: "English (New Zealand)", value: "en-NZ" },
  { label: "English (Philippines)", value: "en-PH" },
  { label: "English (Singapore)", value: "en-SG" },
  { label: "English (South Africa)", value: "en-ZA" },
  { label: "English (United Kingdom)", value: "en-GB" },
  { label: "English (United States)", value: "en-US" },
  { label: "Estonian", value: "et" },
  { label: "Estonian (Estonia)", value: "et-EE" },
  { label: "Filipino", value: "fil" },
  { label: "Filipino (Philippines)", value: "fil-PH" },
  { label: "Finnish", value: "fi" },
  { label: "Finnish (Finland)", value: "fi-FI" },
  { label: "French", value: "fr" },
  { label: "French (Belgium)", value: "fr-BE" },
  { label: "French (Canada)", value: "fr-CA" },
  { label: "French (France)", value: "fr-FR" },
  { label: "French (Luxembourg)", value: "fr-LU" },
  { label: "French (Switzerland)", value: "fr-CH" },
  { label: "Galician", value: "gl" },
  { label: "Galician (Spain)", value: "gl-ES" },
  { label: "Georgian", value: "ka" },
  { label: "Georgian (Georgia)", value: "ka-GE" },
  { label: "German", value: "de" },
  { label: "German (Austria)", value: "de-AT" },
  { label: "German (Germany)", value: "de-DE" },
  { label: "German (Liechtenstein)", value: "de-LI" },
  { label: "German (Luxembourg)", value: "de-LU" },
  { label: "German (Switzerland)", value: "de-CH" },
  { label: "Greek", value: "el" },
  { label: "Greek (Cyprus)", value: "el-CY" },
  { label: "Greek (Greece)", value: "el-GR" },
  { label: "Gujarati", value: "gu" },
  { label: "Gujarati (India)", value: "gu-IN" },
  { label: "Hebrew", value: "he" },
  { label: "Hebrew (Israel)", value: "he-IL" },
  { label: "Hindi", value: "hi" },
  { label: "Hindi (India)", value: "hi-IN" },
  { label: "Hungarian", value: "hu" },
  { label: "Hungarian (Hungary)", value: "hu-HU" },
  { label: "Icelandic", value: "is" },
  { label: "Icelandic (Iceland)", value: "is-IS" },
  { label: "Indonesian", value: "id" },
  { label: "Indonesian (Indonesia)", value: "id-ID" },
  { label: "Irish", value: "ga" },
  { label: "Irish (Ireland)", value: "ga-IE" },
  { label: "Italian", value: "it" },
  { label: "Italian (Italy)", value: "it-IT" },
  { label: "Italian (Switzerland)", value: "it-CH" },
  { label: "Japanese", value: "ja" },
  { label: "Japanese (Japan)", value: "ja-JP" },
  { label: "Kannada", value: "kn" },
  { label: "Kannada (India)", value: "kn-IN" },
  { label: "Kazakh", value: "kk" },
  { label: "Kazakh (Kazakhstan)", value: "kk-KZ" },
  { label: "Khmer", value: "km" },
  { label: "Khmer (Cambodia)", value: "km-KH" },
  { label: "Korean", value: "ko" },
  { label: "Korean (South Korea)", value: "ko-KR" },
  { label: "Kyrgyz", value: "ky" },
  { label: "Kyrgyz (Kyrgyzstan)", value: "ky-KG" },
  { label: "Lao", value: "lo" },
  { label: "Lao (Laos)", value: "lo-LA" },
  { label: "Latvian", value: "lv" },
  { label: "Latvian (Latvia)", value: "lv-LV" },
  { label: "Lithuanian", value: "lt" },
  { label: "Lithuanian (Lithuania)", value: "lt-LT" },
  { label: "Macedonian", value: "mk" },
  { label: "Macedonian (North Macedonia)", value: "mk-MK" },
  { label: "Malay", value: "ms" },
  { label: "Malay (Brunei)", value: "ms-BN" },
  { label: "Malay (Malaysia)", value: "ms-MY" },
  { label: "Malay (Singapore)", value: "ms-SG" },
  { label: "Malayalam", value: "ml" },
  { label: "Malayalam (India)", value: "ml-IN" },
  { label: "Maltese", value: "mt" },
  { label: "Maltese (Malta)", value: "mt-MT" },
  { label: "Marathi", value: "mr" },
  { label: "Marathi (India)", value: "mr-IN" },
  { label: "Mongolian", value: "mn" },
  { label: "Mongolian (Mongolia)", value: "mn-MN" },
  { label: "Nepali", value: "ne" },
  { label: "Nepali (Nepal)", value: "ne-NP" },
  { label: "Norwegian", value: "no" },
  { label: "Norwegian Bokmål", value: "nb" },
  { label: "Norwegian Bokmål (Norway)", value: "nb-NO" },
  { label: "Norwegian Nynorsk", value: "nn" },
  { label: "Norwegian Nynorsk (Norway)", value: "nn-NO" },
  { label: "Pashto", value: "ps" },
  { label: "Pashto (Afghanistan)", value: "ps-AF" },
  { label: "Persian", value: "fa" },
  { label: "Persian (Afghanistan)", value: "fa-AF" },
  { label: "Persian (Iran)", value: "fa-IR" },
  { label: "Polish", value: "pl" },
  { label: "Polish (Poland)", value: "pl-PL" },
  { label: "Portuguese", value: "pt" },
  { label: "Portuguese (Angola)", value: "pt-AO" },
  { label: "Portuguese (Brazil)", value: "pt-BR" },
  { label: "Portuguese (Portugal)", value: "pt-PT" },
  { label: "Punjabi", value: "pa" },
  { label: "Punjabi (India)", value: "pa-IN" },
  { label: "Punjabi (Pakistan)", value: "pa-PK" },
  { label: "Romanian", value: "ro" },
  { label: "Romanian (Moldova)", value: "ro-MD" },
  { label: "Romanian (Romania)", value: "ro-RO" },
  { label: "Russian", value: "ru" },
  { label: "Russian (Belarus)", value: "ru-BY" },
  { label: "Russian (Kazakhstan)", value: "ru-KZ" },
  { label: "Russian (Kyrgyzstan)", value: "ru-KG" },
  { label: "Russian (Moldova)", value: "ru-MD" },
  { label: "Russian (Russia)", value: "ru-RU" },
  { label: "Russian (Ukraine)", value: "ru-UA" },
  { label: "Serbian", value: "sr" },
  { label: "Serbian (Cyrillic)", value: "sr-Cyrl" },
  { label: "Serbian (Latin)", value: "sr-Latn" },
  { label: "Serbian (Serbia)", value: "sr-RS" },
  { label: "Sinhala", value: "si" },
  { label: "Sinhala (Sri Lanka)", value: "si-LK" },
  { label: "Slovak", value: "sk" },
  { label: "Slovak (Slovakia)", value: "sk-SK" },
  { label: "Slovenian", value: "sl" },
  { label: "Slovenian (Slovenia)", value: "sl-SI" },
  { label: "Somali", value: "so" },
  { label: "Somali (Somalia)", value: "so-SO" },
  { label: "Spanish", value: "es" },
  { label: "Spanish (Argentina)", value: "es-AR" },
  { label: "Spanish (Bolivia)", value: "es-BO" },
  { label: "Spanish (Chile)", value: "es-CL" },
  { label: "Spanish (Colombia)", value: "es-CO" },
  { label: "Spanish (Costa Rica)", value: "es-CR" },
  { label: "Spanish (Cuba)", value: "es-CU" },
  { label: "Spanish (Dominican Republic)", value: "es-DO" },
  { label: "Spanish (Ecuador)", value: "es-EC" },
  { label: "Spanish (El Salvador)", value: "es-SV" },
  { label: "Spanish (Equatorial Guinea)", value: "es-GQ" },
  { label: "Spanish (Guatemala)", value: "es-GT" },
  { label: "Spanish (Honduras)", value: "es-HN" },
  { label: "Spanish (Latin America)", value: "es-419" },
  { label: "Spanish (Mexico)", value: "es-MX" },
  { label: "Spanish (Nicaragua)", value: "es-NI" },
  { label: "Spanish (Panama)", value: "es-PA" },
  { label: "Spanish (Paraguay)", value: "es-PY" },
  { label: "Spanish (Peru)", value: "es-PE" },
  { label: "Spanish (Puerto Rico)", value: "es-PR" },
  { label: "Spanish (Spain)", value: "es-ES" },
  { label: "Spanish (United States)", value: "es-US" },
  { label: "Spanish (Uruguay)", value: "es-UY" },
  { label: "Spanish (Venezuela)", value: "es-VE" },
  { label: "Swahili", value: "sw" },
  { label: "Swahili (Kenya)", value: "sw-KE" },
  { label: "Swahili (Tanzania)", value: "sw-TZ" },
  { label: "Swedish", value: "sv" },
  { label: "Swedish (Finland)", value: "sv-FI" },
  { label: "Swedish (Sweden)", value: "sv-SE" },
  { label: "Tagalog", value: "tl" },
  { label: "Tagalog (Philippines)", value: "tl-PH" },
  { label: "Tamil", value: "ta" },
  { label: "Tamil (India)", value: "ta-IN" },
  { label: "Tamil (Malaysia)", value: "ta-MY" },
  { label: "Tamil (Singapore)", value: "ta-SG" },
  { label: "Tamil (Sri Lanka)", value: "ta-LK" },
  { label: "Telugu", value: "te" },
  { label: "Telugu (India)", value: "te-IN" },
  { label: "Thai", value: "th" },
  { label: "Thai (Thailand)", value: "th-TH" },
  { label: "Turkish", value: "tr" },
  { label: "Turkish (Cyprus)", value: "tr-CY" },
  { label: "Turkish (Turkey)", value: "tr-TR" },
  { label: "Ukrainian", value: "uk" },
  { label: "Ukrainian (Ukraine)", value: "uk-UA" },
  { label: "Urdu", value: "ur" },
  { label: "Urdu (India)", value: "ur-IN" },
  { label: "Urdu (Pakistan)", value: "ur-PK" },
  { label: "Uzbek", value: "uz" },
  { label: "Uzbek (Uzbekistan)", value: "uz-UZ" },
  { label: "Vietnamese", value: "vi" },
  { label: "Vietnamese (Vietnam)", value: "vi-VN" },
  { label: "Welsh", value: "cy" },
  { label: "Welsh (United Kingdom)", value: "cy-GB" },
  { label: "Xhosa", value: "xh" },
  { label: "Xhosa (South Africa)", value: "xh-ZA" },
  { label: "Yiddish", value: "yi" },
  { label: "Zulu", value: "zu" },
  { label: "Zulu (South Africa)", value: "zu-ZA" },
] as const

export type Language = typeof languages[number]
export type LanguageValue = Language["value"]
export type LanguageLabel = Language["label"]
